# Generated by Django 3.2.6 on 2022-01-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipescrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='protein',
        ),
    ]
