# Generated by Django 3.2.6 on 2022-01-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipescrap', '0002_auto_20220113_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recipes',
        ),
    ]
