# Generated by Django 3.2.6 on 2022-01-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipescrap', '0003_delete_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('calories', models.CharField(max_length=100)),
                ('protein', models.CharField(max_length=100)),
                ('fat', models.CharField(max_length=100)),
                ('carbs', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
