# Generated by Django 3.2.6 on 2022-01-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipescrap', '0004_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_name',
            field=models.IntegerField(max_length=100),
        ),
    ]
