# Generated by Django 3.2.6 on 2022-01-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipescrap', '0007_auto_20220125_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='carbs',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='fat',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='protein',
            field=models.IntegerField(max_length=100),
        ),
    ]
